// <auto-generated />
namespace BGC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Add_MustChangePassword_Option : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_MustChangePassword_Option));
        
        string IMigrationMetadata.Id
        {
            get { return "201503181146205_Add_MustChangePassword_Option"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
