// <auto-generated />
namespace BGC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Permission_Refactoring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Permission_Refactoring));
        
        string IMigrationMetadata.Id
        {
            get { return "201705292047252_Permission_Refactoring"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
