// <auto-generated />
namespace BGC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class GlossaryDefinition_Term : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GlossaryDefinition_Term));
        
        string IMigrationMetadata.Id
        {
            get { return "201708052030157_GlossaryDefinition_Term"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
