// <auto-generated />
namespace BGC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Glosssary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Glosssary));
        
        string IMigrationMetadata.Id
        {
            get { return "201708051247594_Glosssary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
