language: csharp
solution: BG_Composers.sln
install:
  - nuget restore BG_Composers.sln
  - nuget install NUnit.Console -Version 3.7.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release BG_Composers.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./BGC.Core.Tests/bin/Release/BGC.Core.Tests.dll
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./BGC.Services.Tests/bin/Release/BGC.Services.Tests.dll
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./BGC.Utilities.Tests/bin/Release/BGC.Utilities.Tests.dll
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./BGC.Web.Tests/bin/Release/BGC.Web.Tests.dll
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./CodeShieldTests/bin/Release/CodeShieldTests.dll