using Microsoft.AspNet.Identity;
using Moq;
using NUnit.Framework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BGC.Core.Tests.Models.Identity
{
    [TestFixture]
    public class BgcUserManagerTests
    {
        public class BgcUserManagerProxy : BgcUserManager
        {
            public BgcUserManagerProxy(IUserStore<BgcUser, long> store) :
                base(store)
            {
            }

            public int UserUpdatesCalled { get; set; }

            public override Task<IdentityResult> UpdateAsync(BgcUser user) => Task.Run(() =>
            {
                UserUpdatesCalled++;
                return new IdentityResult();
            });
        }
        [Test]
        public void PasswordResetTokenGenerationTest()
        {
            Mock<IUserTokenProvider<BgcUser, long>> mockTokenProvider = new Mock<IUserTokenProvider<BgcUser, long>>();
            mockTokenProvider.Setup(t => t.GenerateAsync(It.IsAny<string>(), It.IsAny<UserManager<BgcUser, long>>(), It.IsAny<BgcUser>())).ReturnsAsync("token");

            Mock<IUserStore<BgcUser, long>> mockStore = new Mock<IUserStore<BgcUser, long>>();
            var user = new BgcUser() { Id = 5 };
            mockStore.Setup(store => store.FindByIdAsync(user.Id)).ReturnsAsync(user);

            var manager = new BgcUserManagerProxy(mockStore.Object) { UserTokenProvider = mockTokenProvider.Object, EncryptionKey = "password" };
            manager.GeneratePasswordResetToken(user.Id);
            Assert.IsNotNull(user.PasswordResetTokenHash);
            Assert.AreEqual(1, manager.UserUpdatesCalled);
        }

        [Test]
        public void Integration_AcceptsEncryptedTokens()
        {
            Mock<IUserStore<BgcUser, long>> mockStore = new Mock<IUserStore<BgcUser, long>>();
            mockStore.As<IUserPasswordStore<BgcUser, long>>().Setup(x => x.SetPasswordHashAsync(It.IsAny<BgcUser>(), It.IsAny<string>())).Callback((BgcUser u, string pass) =>
            {
                u.PasswordHash = pass;
            });
            var user = new BgcUser() { Id = 5, PasswordHash = "old", Email = "sample_mail@host.com" };
            mockStore.Setup(store => store.FindByIdAsync(user.Id)).ReturnsAsync(user);

            var manager = new BgcUserManagerProxy(mockStore.Object) { UserTokenProvider = new BgcUserTokenProvider(), EncryptionKey = "password" };
            string encryptedToken = manager.GeneratePasswordResetToken(user.Id);
            manager.ResetPasswordAsync(user.Id, encryptedToken, "new").Wait();
            Assert.AreNotEqual("old", user.PasswordHash); // we can't predict the hash generated by ASP.NET Identity, but it certainly won't be "new" or "old"
        }
    }
}
